# Generated by Django 3.2.9 on 2021-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
