# Generated by Django 3.1.5 on 2021-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211114_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
