# Generated by Django 3.1.5 on 2021-11-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211124_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='about_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='about_fr',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='first_name_fr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user_name_en',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user_name_fr',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
