# Generated by Django 3.1.5 on 2021-11-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211124_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(blank=True, default='download.jpeg', null=True, upload_to=''),
        ),
    ]
