# Generated by Django 3.1.5 on 2021-11-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211124_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='user_name_en',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='user_name_fr',
        ),
    ]
